# Generated by Django 3.2.6 on 2021-08-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezepte',
            name='dauer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rezepte',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='rezepte',
            name='zubereitung',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rezepte',
            name='zutaten',
            field=models.TextField(default=''),
        ),
    ]
