# Generated by Django 3.2.6 on 2021-08-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210812_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rezepte',
        ),
    ]
